/*
 * test_parse_sense.c - tests for the decision logic in mega_progress.c.
 *
 * These tools cannot be exercised against a MegaRAID controller in CI, so the
 * three pure functions that carry the real logic are tested against synthetic
 * inputs instead:
 *
 *   parse_sense()  - decodes REQUEST SENSE data from a possibly hostile drive
 *   classify()     - decides whether the drive is still busy (the completion
 *                    decision that gates "safe to power cycle")
 *   parse_target() - validates the target id that says which drive to destroy
 *
 * Build and run via ./run_tests.sh, which extracts all three straight out of
 * mega_progress.c so the code under test is literally the code that ships;
 * there is no second copy to drift.
 *
 * check() copies each case into an exactly-sized heap buffer before calling
 * parse_sense, so a read past `len` lands outside the allocation. Under the
 * ASan pass that run_tests.sh performs, that turns an out-of-bounds read into a
 * hard failure instead of a silent read of neighbouring test data - without it,
 * every bounds check in the parser could be deleted with the suite still green.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

#define u8  uint8_t
#define u32 uint32_t

/* generated by run_tests.sh from mega_progress.c - not in git */
#include "parse_sense.inc"

static int failures;

/* Expected results of one parse_sense call. When rc is -1 the output
   parameters are not compared, since parse_sense leaves them untouched. */
struct expect {
    int rc;
    int key, asc, ascq;
    int progress;
};

static void check(const char *name, const u8 *buf, size_t len, struct expect e) {
    u8 key = 0xEE, asc = 0xEE, ascq = 0xEE;
    int prog = -99, rc, ok;
    u8 *exact = malloc(len ? len : 1);   /* exact size: overreads leave the object */

    memcpy(exact, buf, len);
    rc = parse_sense(exact, len, &key, &asc, &ascq, &prog);
    ok = (rc == e.rc) &&
         (rc != 0 || (key == e.key && asc == e.asc &&
                      ascq == e.ascq && prog == e.progress));
    free(exact);

    printf("%-58s %s\n", name, ok ? "PASS" : "FAIL");
    if (!ok) {
        failures++;
        printf("     got      rc=%d key=0x%x asc=0x%02x ascq=0x%02x prog=%d\n",
               rc, key, asc, ascq, prog);
        printf("     expected rc=%d key=0x%x asc=0x%02x ascq=0x%02x prog=%d\n",
               e.rc, e.key, e.asc, e.ascq, e.progress);
    }
}

static void check_state(const char *name, u8 sense_key, u8 asc, u8 ascq,
                        int progress, enum drive_state expected) {
    enum drive_state got = classify(sense_key, asc, ascq, progress);
    int ok = (got == expected);

    printf("%-58s %s\n", name, ok ? "PASS" : "FAIL");
    if (!ok) {
        failures++;
        printf("     got state %d, expected %d\n", (int)got, (int)expected);
    }
}

static void check_target(const char *name, const char *arg, int expected) {
    int got = parse_target(arg);
    int ok = (got == expected);

    printf("%-58s %s\n", name, ok ? "PASS" : "FAIL");
    if (!ok) {
        failures++;
        printf("     parse_target(\"%s\") = %d, expected %d\n", arg, got, expected);
    }
}

int main(void) {
    u8 b[96];

    /* ================= parse_sense: fixed format =================
     * SPC-4 fixed format byte offsets:
     *    0  response code (0x70 current, 0x71 deferred; bit 7 = VALID)
     *    2  sense key (low nibble)
     *    7  additional sense length (bytes beyond byte 7)
     *   12  ASC        13  ASCQ
     *   15  SKSV in bit 7      16-17  progress indication (big endian)
     */

    memset(b, 0, sizeof b);
    b[0] = 0x70; b[2] = 0x02; b[7] = 0x0a; b[12] = 0x04; b[13] = 0x04;
    b[15] = 0x80; b[16] = 0x6b; b[17] = 0x84;
    check("fixed / NOT READY 04/04 / SKSV=1", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = 0x6b84 });

    memset(b, 0, sizeof b);
    b[0] = 0x71; b[2] = 0x02; b[7] = 0x0a; b[12] = 0x04; b[13] = 0x04;
    b[15] = 0x80; b[16] = 0x6b; b[17] = 0x84;
    check("fixed / DEFERRED (0x71) decodes like 0x70", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = 0x6b84 });

    memset(b, 0, sizeof b);
    b[0] = 0xF0; b[2] = 0x02; b[7] = 0x0a; b[12] = 0x04; b[13] = 0x04;
    check("fixed / VALID bit (0xF0) is still response code 0x70", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = -1 });

    memset(b, 0, sizeof b);
    b[0] = 0x70; b[2] = 0x02; b[7] = 0x0a; b[12] = 0x04; b[13] = 0x04;
    b[15] = 0x00; b[16] = 0x6b; b[17] = 0x84;
    check("fixed / SKSV=0 suppresses progress", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = -1 });

    memset(b, 0, sizeof b);
    b[0] = 0x70; b[7] = 0x0a;
    check("fixed / NO SENSE, nothing reported", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x00, .asc = 0x00, .ascq = 0x00, .progress = -1 });

    /* A drive may format in the background while keeping the LU accessible,
       reporting NO SENSE with a valid progress field. Treating that as a
       finished format would tell an operator it is safe to power cycle. */
    memset(b, 0, sizeof b);
    b[0] = 0x70; b[2] = 0x00; b[7] = 0x0a;
    b[15] = 0x80; b[16] = 0x40; b[17] = 0x00;
    check("fixed / NO SENSE + SKSV progress is surfaced", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x00, .asc = 0x00, .ascq = 0x00, .progress = 0x4000 });

    /* Under ILLEGAL REQUEST these bytes are a pointer to the offending CDB
       field, not progress. Rendering that as a percentage would be worse than
       reporting nothing. */
    memset(b, 0, sizeof b);
    b[0] = 0x70; b[2] = 0x05; b[7] = 0x0a; b[12] = 0x24; b[13] = 0x00;
    b[15] = 0x80; b[16] = 0x00; b[17] = 0x01;
    check("fixed / ILLEGAL REQUEST field pointer is NOT progress", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x05, .asc = 0x24, .ascq = 0x00, .progress = -1 });

    /* Under MEDIUM ERROR they are an actual retry count. */
    memset(b, 0, sizeof b);
    b[0] = 0x70; b[2] = 0x03; b[7] = 0x0a; b[12] = 0x11; b[13] = 0x00;
    b[15] = 0x80; b[16] = 0x00; b[17] = 0x07;
    check("fixed / MEDIUM ERROR retry count is NOT progress", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x03, .asc = 0x11, .ascq = 0x00, .progress = -1 });

    memset(b, 0, sizeof b);
    b[0] = 0x70; b[2] = 0x02; b[7] = 0x00; b[12] = 0x04; b[13] = 0x04;
    check("fixed / additional length 0 suppresses ASC/ASCQ", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x00, .ascq = 0x00, .progress = -1 });

    memset(b, 0, sizeof b);
    b[0] = 0x70;
    check("fixed / below the 8-byte header (len=4)", b, 4, (struct expect){ .rc = -1 });

    /* BOUNDS: the drive declares 10 more bytes than the buffer holds. Without
       the `valid > len` clamp the parser reads the planted SKSV and progress
       past the end of the allocation. */
    memset(b, 0, sizeof b);
    b[0] = 0x70; b[2] = 0x02; b[7] = 0x0a; b[12] = 0x04; b[13] = 0x04;
    b[15] = 0x80; b[16] = 0x9a; b[17] = 0xbc;
    /* ASC/ASCQ at 12-13 are inside len and stay readable; the point is that
       the progress bytes at 15-17 are not read. */
    check("fixed / BOUNDS: declared length overruns len=14", b, 14,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = -1 });

    /* ================= parse_sense: descriptor format =================
     * SPC-4 descriptor format:
     *    0  response code (0x72 current, 0x73 deferred)
     *    1  sense key    2  ASC    3  ASCQ
     *    7  additional length (total size of the descriptor list)
     *    8.. descriptor list; each descriptor: +0 type, +1 additional length
     *        type 0x02 (sense-key specific): +4 SKSV bit 7, +5..+6 progress
     *        type 0x0A (another progress indication): +6..+7 progress, no SKSV
     *
     * We send REQUEST SENSE with DESC=0, so a conformant drive never returns
     * this format; these cover the defensive path.
     */

    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x08;
    b[8] = 0x02; b[9] = 0x06; b[12] = 0x80; b[13] = 0x6b; b[14] = 0x84;
    check("descriptor / type 0x02 SKSV=1", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = 0x6b84 });

    memset(b, 0, sizeof b);
    b[0] = 0x73; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x08;
    b[8] = 0x02; b[9] = 0x06; b[12] = 0x80; b[13] = 0x6b; b[14] = 0x84;
    check("descriptor / DEFERRED (0x73) decodes like 0x72", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = 0x6b84 });

    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x08;
    b[8] = 0x02; b[9] = 0x06; b[12] = 0x00; b[13] = 0x6b; b[14] = 0x84;
    check("descriptor / type 0x02 SKSV=0 suppresses progress", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = -1 });

    /* The sense-key gate applies to the descriptor branch too, not just fixed. */
    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x05; b[2] = 0x24; b[3] = 0x00; b[7] = 0x08;
    b[8] = 0x02; b[9] = 0x06; b[12] = 0x80; b[13] = 0x00; b[14] = 0x01;
    check("descriptor / ILLEGAL REQUEST field pointer is NOT progress", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x05, .asc = 0x24, .ascq = 0x00, .progress = -1 });

    /* Type 0x0A carries its own sense key / ASC / ASCQ at +2..+4. */
    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x08;
    b[8] = 0x0a; b[9] = 0x06; b[10] = 0x02; b[11] = 0x04; b[12] = 0x04;
    b[14] = 0x20; b[15] = 0x00;
    check("descriptor / type 0x0A fallback", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = 0x2000 });

    /* Type 0x02 must win over 0x0A even when 0x0A comes first in the list. */
    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x10;
    b[8] = 0x0a; b[9] = 0x06; b[14] = 0x20; b[15] = 0x00;
    b[16] = 0x02; b[17] = 0x06; b[20] = 0x80; b[21] = 0x6b; b[22] = 0x84;
    check("descriptor / type 0x02 wins over an earlier 0x0A", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = 0x6b84 });

    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x14;
    b[8] = 0x00; b[9] = 0x0a;                       /* information descriptor */
    b[20] = 0x02; b[21] = 0x06; b[24] = 0x80; b[25] = 0x30; b[26] = 0x00;
    check("descriptor / SKS after an information descriptor", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = 0x3000 });

    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x00;
    check("descriptor / no descriptors present", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = -1 });

    /* BOUNDS: a descriptor claiming 257 bytes inside an 8-byte list. The
       planted SKSV+progress at 12..14 is what the parser reads if the
       `i + dlen > end` check is missing, so this case fails without it. */
    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x08;
    b[8] = 0x02; b[9] = 0xff;
    b[12] = 0x80; b[13] = 0x12; b[14] = 0x34;
    check("descriptor / BOUNDS: descriptor lying about its length", b, sizeof b,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = -1 });

    /* BOUNDS: additional length declares 64 bytes of descriptors but the
       buffer is 16. Without the `end > len` clamp the walk runs past the
       allocation and finds the live descriptor planted at 16. */
    memset(b, 0, sizeof b);
    b[0] = 0x72; b[1] = 0x02; b[2] = 0x04; b[3] = 0x04; b[7] = 0x40;
    b[8] = 0x00; b[9] = 0x06;
    b[16] = 0x02; b[17] = 0x06; b[20] = 0x80; b[21] = 0x56; b[22] = 0x78;
    check("descriptor / BOUNDS: additional length overruns len=16", b, 16,
          (struct expect){ .rc = 0, .key = 0x02, .asc = 0x04, .ascq = 0x04, .progress = -1 });

    /* ================= malformed ================= */

    memset(b, 0, sizeof b);
    check("unrecognized response code 0x00", b, sizeof b, (struct expect){ .rc = -1 });

    memset(b, 0, sizeof b);
    b[0] = 0x7F;
    check("unrecognized response code 0x7F", b, sizeof b, (struct expect){ .rc = -1 });

    /* ================= classify(): the completion decision ================= */

    check_state("classify / NOT READY 04/04 -> FORMATTING",
                0x02, 0x04, 0x04, 0x1000, STATE_FORMATTING);
    check_state("classify / NO SENSE 04/04 -> FORMATTING",
                0x00, 0x04, 0x04, 0x1000, STATE_FORMATTING);
    check_state("classify / 04/04 without progress -> FORMATTING",
                0x02, 0x04, 0x04, -1, STATE_FORMATTING);
    check_state("classify / NOT READY 04/01 becoming ready -> NOT_READY",
                0x02, 0x04, 0x01, -1, STATE_NOT_READY);
    /* The case the third commit exists to fix: a background operation reported
       without 04/04 must not read as a finished format. */
    check_state("classify / NO SENSE + progress, no 04/04 -> BACKGROUND_OP",
                0x00, 0x00, 0x00, 0x2000, STATE_BACKGROUND_OP);
    check_state("classify / UNIT ATTENTION -> UNIT_ATTENTION",
                0x06, 0x29, 0x00, -1, STATE_UNIT_ATTENTION);
    check_state("classify / NO SENSE, nothing pending -> IDLE",
                0x00, 0x00, 0x00, -1, STATE_IDLE);
    check_state("classify / RECOVERED ERROR, no progress -> IDLE",
                0x01, 0x00, 0x00, -1, STATE_IDLE);

    /* ================= parse_target(): which drive gets destroyed ========= */

    check_target("parse_target / \"0\"", "0", 0);
    check_target("parse_target / \"4\"", "4", 4);
    check_target("parse_target / \"255\"", "255", 255);
    check_target("parse_target / \"256\" out of range", "256", -1);
    check_target("parse_target / \"-1\" negative", "-1", -1);
    check_target("parse_target / \"4x\" trailing garbage", "4x", -1);
    check_target("parse_target / \"abc\" not a number", "abc", -1);
    check_target("parse_target / \"\" empty", "", -1);
    check_target("parse_target / \"0x04\" is not hex here", "0x04", -1);
    check_target("parse_target / \"99999999999999999999\" overflow", "99999999999999999999", -1);
    /* strtol skips leading whitespace and accepts a sign; both still yield
       exactly the number written, so neither can select an unintended drive. */
    check_target("parse_target / \" 4\" leading space accepted", " 4", 4);
    check_target("parse_target / \"+4\" sign accepted", "+4", 4);

    printf("\n%s (%d failure%s)\n", failures ? "FAILURES" : "all tests passed",
           failures, failures == 1 ? "" : "s");
    return failures != 0;
}
